import { getToolsFromOpenApi } from './generator/api';
import fs from 'fs';
import type { McpToolDefinition } from '../src/types/mcp-tool-definition';

(async () => {
  const tools: McpToolDefinition[] = await getToolsFromOpenApi('https://api-docs.firefly-iii.org/firefly-iii-6.2.13-v1.yaml');

  // Create the TypeScript code string
  const tsCode = `// This file is auto-generated by scripts/generator.ts

import type { McpToolDefinition } from '../types/mcp-tool-definition';

export const generatedTools: McpToolDefinition[] = ${JSON.stringify(tools, null, 2)};
`;

  fs.writeFileSync('./src/definitions/tools.ts', tsCode);
  console.log('Successfully generated generated-tools.ts');
})();